### ISSUE TITLE
How to install the script on serverpilot setup

### ISSUE THREAD

**Issue by q2apro** [sierracircle/services-checker#1]
I am rather new to the "server world" and am actually using serverpilot.io (that installs all the necessary components for web, mainly LAMP). 

I am also running a droplet using digitalocean. You recommended your script [there](https://www.digitalocean.com/community/questions/alert-notification-when-server-is-down). 

Now I would like to install the script but do not know how. You start with `1. put into your scripts folder`, could you just give an example of the how-to? And is this a special folder or can you define it yourself? Can I just upload it via FTP? Is the file `services` a SH file?

PS: I already found out how to do the [cronjob setup](https://serverpilot.io/community/articles/how-to-use-cron-to-schedule-scripts.html) via serverpilot.

**Comment by sierracircle** [comment]
Hi Kai,
  The script is just the one file. I say "scripts folder"  but you can put it anywhere. Generally, I create a script folder  because I have other scripts, so I just keep them all in one place.
   If you are using SSH, you can do the following:

Use ssh to create a folder for your scripts:
`mkdir ~/.scripts`

   then use sFTP to upload the script to that folder you just created

  then (with ssh) chmod the script to make it executable:
`chmod +x  ~/.scripts/services`

 after that, you can test it with the following:

 stop apache:
`sudo service apache2 stop`

then run the script to see if it restarts apache:
`sudo ~/.scripts/services`

check your website. If apache is running, the script is working! You should also have received an email.

**Comment by sierracircle** [comment]
closing the issue, as I never heard back from original poster

**Comment by q2apro** [comment]
Hi sierracircle, thanks a lot for your description. I still have not had time to implement it. 

I copied the script on my server as you said. However, I am on Digital Ocean with Serverpilot and need to setup the cronjobs to test. 

I will report back, hopefully next week, when I am done and if it worked.

Thanks for your efforts!

**Comment by q2apro** [comment]
Tried your tutorial, but get after `sudo service apache2 stop`: 

> Failed to stop apache2.service: Unit apache2.service not loaded.

Guess the apache service is called `apache-sp` [with serverpilot](https://serverpilot.io/community/articles/customize-apache-settings.html)?

Guess too that I need to rename the `apache2` in your script to `apache-sp`?

**Comment by sierracircle** [comment]
try running this on a terminal:
`sudo service apache-sp reload`

If that indeed works, then yes, you will change the line in the script to reflect that:
`
SERVICES=( 'apache-sp' 'mysql' )`

in fact, you can change that line to whatever services you want to monitor ... (on some of my droplets I only have a webserver, and use a different droplet for mysql..so for each server, on that line  I list the services that I want to monitor for that droplet running (openvpn, etc..)

**Comment by q2apro** [comment]
Restart works, I used `sudo service apache-sp restart`. 

I wanted to run your script, which is in my `/srv/users/serverpilot/apps/scripts/` folder, however, using `sudo services` now leads to `sudo: services: command not found`.

Do I have to rename the file `services` to `services.sh`?

**Comment by sierracircle** [comment]
services shoudl work, but you have to give the full path, so your command will be:
`sudo /srv/users/serverpilot/apps/scripts/services`

**Comment by q2apro** [comment]
Thanks, now it works. The output is: 

```
 mysql.service - MySQL Community Server
   Loaded: loaded (/lib/systemd/system/mysql.service; enabled; vendor preset: en
  Drop-In: /etc/systemd/system/mysql.service.d
           └─open_files_limit.conf
   Active: active (running) since Wed 2016-09-14 00:38:55 CEST; 5 days ago
 Main PID: 24210 (mysqld)
    Tasks: 35
   Memory: 936.8M
      CPU: 19h 29min 25.263s
   CGroup: /system.slice/mysql.service
           └─24210 /usr/sbin/mysqld

Sep 14 00:38:54 box.mydomain.com systemd[1]: Stopped MySQL Community Server.
Sep 14 00:38:54 box.mydomain.com systemd[1]: Starting MySQL Community Server..
Sep 14 00:38:55 box.mydomain.com systemd[1]: Started MySQL Community Server.
```

But it says nothing about apache-sp. Since I am new to the shell :) I am quite careful with my inputs. So until here, everything is okay? 

**EDIT:**

I called it again (before I obviously did not have the entire output), this is the second half of the output: 

```
 apache-sp.service - LSB: Start/stop apache web server
   Loaded: loaded (/etc/init.d/apache-sp; bad; vendor preset: enabled)
   Active: active (running) since Sun 2016-09-18 20:29:13 CEST; 7h ago
     Docs: man:systemd-sysv-generator(8)
  Process: 27153 ExecStop=/etc/init.d/apache-sp stop (code=exited, status=0/SUCCESS)
  Process: 27169 ExecStart=/etc/init.d/apache-sp start (code=exited, status=0/SUCCESS)
    Tasks: 110
   Memory: 64.0M
      CPU: 5min 2.440s
   CGroup: /system.slice/apache-sp.service
           ├─27178 /opt/sp/apache/bin/httpd -k start
           ├─27180 /opt/sp/apache/bin/httpd -k start
           ├─27181 /opt/sp/apache/bin/httpd -k start
           ├─27183 /opt/sp/apache/bin/httpd -k start
           ├─27185 /opt/sp/apache/bin/httpd -k start
           └─27265 /opt/sp/apache/bin/httpd -k start

Sep 18 20:29:12 box.example.com systemd[1]: Starting LSB: Start/stop apache web server...
Sep 18 20:29:13 box.example.com apache-sp[27169]: Starting apache.
Sep 18 20:29:13 box.example.com systemd[1]: Started LSB: Start/stop apache web server.
```

**Comment by sierracircle** [comment]
what is the command that is the output of? Is that the script? If so, were apache and Mysql already started?

You can test the script by putting it on a cron and then stopping Mysql:

sudo service mysql stop

then see if the script restarts it.

**Comment by q2apro** [comment]
The one you specified at last: `sudo /srv/users/serverpilot/apps/scripts/services`

**Comment by q2apro** [comment]
The one you specified at last: `sudo /srv/users/serverpilot/apps/scripts/services`

Okay, I have stopped apache-sp. Then I called your services-script. Result: It restarted :) 

```
● apache-sp.service - LSB: Start/stop apache web server
   Loaded: loaded (/etc/init.d/apache-sp; bad; vendor preset: enabled)
   Active: inactive (dead) since Mon 2016-09-19 04:53:52 CEST; 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 571 ExecStop=/etc/init.d/apache-sp stop (code=exited, status=0/SUCCESS)
  Process: 415 ExecStart=/etc/init.d/apache-sp start (code=exited, status=0/SUCCESS)

Sep 19 04:53:23 box.mydomain.com systemd[1]: Starting LSB: Start/stop apache web server...
Sep 19 04:53:24 box.mydomain.com apache-sp[415]: Starting apache.
Sep 19 04:53:24 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 19 04:53:51 box.mydomain.com systemd[1]: Stopping LSB: Start/stop apache web server...
Sep 19 04:53:52 box.mydomain.com apache-sp[571]: Stopping apache.
Sep 19 04:53:52 box.mydomain.com systemd[1]: Stopped LSB: Start/stop apache web server.
● apache-sp.service - LSB: Start/stop apache web server
   Loaded: loaded (/etc/init.d/apache-sp; bad; vendor preset: enabled)
   Active: active (running) since Mon 2016-09-19 04:53:56 CEST; 10ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 571 ExecStop=/etc/init.d/apache-sp stop (code=exited, status=0/SUCCESS)
  Process: 626 ExecStart=/etc/init.d/apache-sp start (code=exited, status=0/SUCCESS)
    Tasks: 86
   Memory: 12.0M
      CPU: 121ms
   CGroup: /system.slice/apache-sp.service
           ├─633 /opt/sp/apache/bin/httpd -k start
           ├─635 /opt/sp/apache/bin/httpd -k start
           ├─636 /opt/sp/apache/bin/httpd -k start
           ├─638 /opt/sp/apache/bin/httpd -k start
           └─652 /opt/sp/apache/bin/httpd -k start

Sep 19 04:53:55 box.mydomain.com systemd[1]: Starting LSB: Start/stop apache web server...
Sep 19 04:53:56 box.mydomain.com apache-sp[626]: Starting apache.
Sep 19 04:53:56 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
```

And I have received the email, subject "Re: apache-sp down -but restarted-  on box.mydomain.com Mon Sep 19 04:53:56 CEST 2016": 

```
apache-sp  [Mon Sep 19 04:53:51.955983 2016] [mpm_event:notice] [pid 422:tid 140443132852096] AH00491: caught SIGTERM, shutting down
[Mon Sep 19 04:53:55.906592 2016] [suexec:notice] [pid 632:tid 140542458988416] AH01232: suEXEC mechanism enabled (wrapper: /opt/sp/apache/bin/suexec)
[Mon Sep 19 04:53:55.952394 2016] [auth_digest:notice] [pid 633:tid 140542458988416] AH01757: generating secret for digest authentication ...
[Mon Sep 19 04:53:55.956910 2016] [mpm_event:notice] [pid 633:tid 140542458988416] AH00489: Apache/2.4.18 (Unix) OpenSSL/1.0.2g-fips configured -- resuming normal operations
[Mon Sep 19 04:53:55.956930 2016] [core:notice] [pid 633:tid 140542458988416] AH00094: Command line: '/opt/sp/apache/bin/httpd' 
```

That looks good, I would say.

**Comment by sierracircle** [comment]
Great. Now you just need to set up your cron and it should work. Let me 
know if you have any issues. All of my tests so far have been with basic 
apache/mysql  so I have not had a chance to test with a server-pilot 
install.

**Comment by q2apro** [comment]
Finishing up by doing the cron job: 

`crontab -e`

Adding an entry for "minutely" execution: 

`# Script to check if apache and mysql are running, restarts if not`
`* * * * * /srv/users/serverpilot/apps/scripts/services`

I stopped apache and waited for > 1 min, but nothing happened. Trying to find out why.

_Btw, still wondering if I should rename the "services" file to "services.sh"_

**Comment by sierracircle** [comment]
You need to add to root crontab, so:

sudo crontab -e

**Comment by q2apro** [comment]
I am logged-in as root. It opens the same file. 

It is also visible when I do `crontab -l`. 

I try to add `MAILTO="my@gmail.com"` to the script so I can see if it works.

**Comment by sierracircle** [comment]
what is the frequency of your cron?

every minute should be fine:

**Comment by q2apro** [comment]
Yes, the `* * * * *` [should lead](https://help.ubuntu.com/community/CronHowto) to execution each minute. 

Ah, got the email (subject "Cron root@box /srv/users/serverpilot/apps/scripts/services") with an error message. Content: 

```
/srv/users/serverpilot/apps/scripts/services: line 22: service: command not found
```

?

I guess it is referencing to line 22 of the script: `service $i status;`

I searched the net and found two [possible reasons](http://askubuntu.com/a/800349/238253) mentioned: 

> 1. an executable not having execute permissions for your user or group
> 2. an executable not belonging to a folder listed in PATH variable , or the opposite - PATH variable that does not contain the location of your executable.

Or this: http://stackoverflow.com/questions/8127433/unable-to-run-a-service-command-via-cron

**Comment by sierracircle** [comment]
Out of curiosity: are you using the current  script  version 4?
Also, have you made the script executable?  sudo chmod +x  /srv/users/serverpilot/apps/scripts/services

**Comment by q2apro** [comment]
I assume that serverpilot does not allow to access self-created folders (in my case "scripts"). So I moved your "services" file into one of the registered `apps` folders. 

The email output: 

```
/bin/sh: 1: /srv/users/serverpilot/apps/MYAPPNAME/services: Permission denied
```

Then I used `chmod +x` again, this time for the newly copied file "services" in the app folder. Then ran the cronjob. Then I get again:

```
/srv/users/serverpilot/apps/MYAPPNAME/services: line 22: service: command not found
```

Oh, there is a new script version?! I checked, it says `#ver. 2`. Updated to the newer version 4 now. 

**Testing again (Cronjob with v. 4):**

Getting an email with: 

> apache-sp is down on box.mydomain.com at Mon Sep 19 05:37:02 CEST 2016  I tried to restart it, but it did not work

However, apache is running all the time.

**Update:** Tried it manually.
1. sudo service apache-sp stop
2. sudo /srv/users/serverpilot/apps/scripts/services

The automatic restart worked.

**Comment by q2apro** [comment]
Tried the `service` script by cronjob, seems to work! 
1. set up the cronjob of `* * * * * /srv/users/serverpilot/apps/scripts/services`
2. stopped Apache by `sudo service apache-sp stop`
3. Loaded the website, got "Bad Gateway"
4. Reloaded the website after some seconds, worked

No email received from the cronjob, means it has permission now and no errors.

However, still no email received from the script informing me about the Apache restart.

**Comment by sierracircle** [comment]
ok...so it is restarting apache, but not sending you the email?  It might have made the tmp file...you can remove it with:  sudo rm /tmp/apache-sp
then try again

**Comment by q2apro** [comment]
**1st attempt stopping apache-sp**

Removed the file "/tmp/apache-sp" firsthand, then stopped service apache-sp manually and yes, the cronjob triggered, and the email was sent. 

Content: 

```
 apache-sp is down on box.mydomain.com at Mon Sep 19 06:39:03 CEST 2016  I tried to restart it, but it did not work
```

Although it did the restart.

**2nd attempt stopping apache-sp**
- manually stopped apache-sp
- cronjob restarted apache-sp
- no email 
- file "apache-sp" to be found in /tmp/ again

**Comment by sierracircle** [comment]
It sounds to me that this will need futher investigating. Since I do not have a ServerPilot setup, I am not in a good position to trouble-shoot; however, if you want to take the time you are welcome to, and I will help where I can.

For starters, I think a simplified version of this script would be the way to trouble-shoot.

Are you comfortable with re-writing the script, or do you need me to help with that?

**Comment by q2apro** [comment]
First time for me that I am using such a script, so programmingwise I might not yet be a great help. 

However, since the script cannot delete the temporary file, I assume that it could be a permission issue. Is there any way to check permission directly from within the script?

**Comment by sierracircle** [comment]
I doubt it is permissions, since you said you are running as root.

My guess is that the script is not getting the correct message when 
asking if a service is running. What happens if you run these three 
lines in a terminal, one after the other:

`pgrep apache-sp >/dev/null 2>&1`
  STATS=$(echo $?)
echo $STATS

**Comment by q2apro** [comment]
Sorry for my late reply. 

The output is simply: `1`

**Comment by sierracircle** [comment]
I was afraid of that..
1 means that is sees the service apache-sp as not on.

Can you do the same thing only with mysql:

```
`pgrep mysql >/dev/null 2>&1` 
STATS=$(echo $?) 
echo $STATS
```

**Comment by q2apro** [comment]
That returns a `0`.

**Comment by sierracircle** [comment]
Ok..so the script is working for mysql, but the service name for apache is not working.
You need to find the name of the apache service for checking the service. You might try:

```
`pgrep apache2 >/dev/null 2>&1` 
STATS=$(echo $?) 
echo $STATS
```

**Comment by q2apro** [comment]
Mhh, this gives me `1` again. 

I was running `service --status-all` and got: `apache-sp` as running.

**Comment by sierracircle** [comment]
run this and post the list that it outputs:
`service --status-all`

**Comment by q2apro** [comment]
Here you go: 

```
root@box:~# service --status-all
[ + ]  acpid
[ + ]  apache-sp
[ + ]  apparmor
[ + ]  apport
[ + ]  atd
[ - ]  bootmisc.sh
[ - ]  checkfs.sh
[ - ]  checkroot-bootclean.sh
[ - ]  checkroot.sh
[ + ]  console-setup
[ + ]  cron
[ - ]  cryptdisks
[ - ]  cryptdisks-early
[ + ]  dbus
[ + ]  grub-common
[ - ]  hostname.sh
[ - ]  hwclock.sh
[ + ]  irqbalance
[ + ]  iscsid
[ + ]  keyboard-setup
[ - ]  killprocs
[ + ]  kmod
[ - ]  lvm2
[ + ]  lvm2-lvmetad
[ + ]  lvm2-lvmpolld
[ + ]  lxcfs
[ - ]  lxd
[ + ]  mdadm
[ - ]  mdadm-waitidle
[ - ]  mountall-bootclean.sh
[ - ]  mountall.sh
[ - ]  mountdevsubfs.sh
[ - ]  mountkernfs.sh
[ - ]  mountnfs-bootclean.sh
[ - ]  mountnfs.sh
[ + ]  mysql
[ + ]  networking
[ + ]  nginx-sp
[ + ]  ondemand
[ + ]  open-iscsi
[ + ]  php5.4-fpm-sp
[ + ]  php5.5-fpm-sp
[ + ]  php5.6-fpm-sp
[ + ]  php7.0-fpm-sp
[ + ]  php7.1-fpm-sp
[ - ]  plymouth
[ - ]  plymouth-log
[ + ]  postfix
[ + ]  procps
[ + ]  rc.local
[ + ]  resolvconf
[ - ]  rsync
[ + ]  rsyslog
[ - ]  screen-cleanup
[ - ]  sendsigs
[ + ]  ssh
[ + ]  udev
[ + ]  ufw
[ - ]  umountfs
[ - ]  umountnfs.sh
[ - ]  umountroot
[ - ]  unattended-upgrades
[ + ]  urandom
[ - ]  uuidd
[ - ]  x11-common
```

**Comment by sierracircle** [comment]
I am stumped. The name of the service is certainly apache-sp, but when you run the check it is not telling you that it is running.
You can spend some time on it, but I am afraid this script will not help you for apache. It will, however, check your mysql service...which is generally what people have issues with mostly.

**Comment by q2apro** [comment]
I am still guessing that the `-` in the name `apache-sp` could be a problem. Do we need to escape it?

**Comment by sierracircle** [comment]
It could be that is the issue. You can try it and see what happens...Also, you might post the question on DigitalOcean forums. Someone there might know. Particurly, you want to know why this does not return 0:

```
`pgrep apache-sp >/dev/null 2>&1`
 STATS=$(echo $?) 
echo $STATS
```

but I have to ask: with all of the work you are putting into this, why not just run your own Apache/Mysql droplet? It is not that difficult, is free (not the droplet, but the services, and once you start learning how to manage your own server your understanding of how things work will broaden.

Does server-pilot offer some features that are unavailable elsewhere? I am curious

**Comment by q2apro** [comment]
Your small script returns `1`

Regarding the "server by myself", it just takes too much time that I do not have currently. I am a mix of manager and developer and cannot spent too much time on such things. Plus, our team is still small, so such things still rely on me. http://www.memelpower.com/

Thanks, however, for all your efforts. This is very much appreciated.

**Comment by sierracircle** [comment]
Yes, the script returns a 1, which is the problem. The script should return a 0 (showing that the service is running)
You will need to find out why that is returning a 1 instead of a 0. If you can discover that, then we can get this working for you.
Otherwise, I would just suggest using it for Mysql and not put any more time into this. My experience is that Apache is not usually the service that has problems...while Mysql will often crash because of bots attacking Wordpress.

**Comment by q2apro** [comment]
I send Serverpilot a question about the issue, maybe they know about it.

**Comment by sierracircle** [comment]
Great! Itwill be interesting to know the answer.

**Comment by q2apro** [comment]
The answer: 

> I'm not sure why that script isn't detecting that apache-sp is running. Can you run this command as root and send me the output? sudo service apache-sp status

```
● apache-sp.service - LSB: Start/stop apache web server
Loaded: loaded (/etc/init.d/apache-sp; bad; vendor preset: enabled)
Active: active (running) since Mon 2016-09-19 06:40:03 CEST; 1 weeks 4 days ago
Docs: man:systemd-sysv-generator(8)
Tasks: 110
Memory: 86.6M
CPU: 4h 21min 48.761s
CGroup: /system.slice/apache-sp.service
├─6456 /opt/sp/apache/bin/httpd -k start
├─9661 /opt/sp/apache/bin/httpd -k start
├─9662 /opt/sp/apache/bin/httpd -k start
├─9663 /opt/sp/apache/bin/httpd -k start
├─9664 /opt/sp/apache/bin/httpd -k start
└─9960 /opt/sp/apache/bin/httpd -k start

Sep 30 18:27:02 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:28:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:29:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:30:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:31:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:32:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:33:02 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:34:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:35:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
Sep 30 18:36:01 box.mydomain.com systemd[1]: Started LSB: Start/stop apache web server.
```

2nd answer: 

> That output is showing that apache-sp is currently running. So I'm not sure why the command you were given is indicating that it isn't running. Unfortunately we can't help determine why a third-party script isn't properly detecting services on the server. You may need to modify the script to detect the service with something like "service apache-sp status".

**Comment by sierracircle** [comment]
Not much of an answer...
You might try posting on DigitalOcean. There might be someone with an answer for testing apache-sp on server-pilot

**Comment by sierracircle** [comment]
it is a longshot, but you can also try this:
`pgrep "apache-sp" >/dev/null 2>&1`
 STATS=$(echo $?) 
echo $STATS

**Comment by q2apro** [comment]
Gives me `1`.
