### ISSUE TITLE
Temp file purpose

### ISSUE THREAD

**Issue by robertg042** [sierracircle/services-checker#13]
Hey, thanks for the script!

Just a question: what's the purpose of the temp file that is created when a service could not be restarted?

**Comment by sierracircle** [comment]
Hi. Good question.  The temp file gives the script something to check against to see if it has already notified you about the service being down.  My original version of this script would just keep emailing over and over, so I came up with the temp file to prevent multiple emails telling you the same thing (and filling up your inbox)

**Comment by robertg042** [comment]
Hah, now it seems obvious :) Thanks for the answer!
