### ISSUE TITLE
Can the script file be renamed from "services" to "services.sh"?

### ISSUE THREAD

**Issue by q2apro** [sierracircle/services-checker#14]
I am new to Linux and just wondering if I can rename "services" to "services.sh"?

Or what is the reason to have no file ending for the script.

Thank you.

**Comment by sierracircle** [comment]
You can rename the script to whatever you want. Linux does not depend on file extensions the way Windows does. In Windows, you have to have .jpg  or .bat or  whatever  on a file or Windows does not know what to do. With Linux that is not necessary.
