### ISSUE TITLE
Keep a log of the reboots maybe?

### ISSUE THREAD

**Issue by jomourad** [sierracircle/services-checker#15]
I don't know if this repo is still alive, but what would be awesome (if it's not already the case?) would be that there's a log file of the reboots (or unsuccessful restarts). Right now, since my server doesn't send out emails (another of my own problems lol) i would like to have a way to verify if the script actually works, AND how often do my services crash.

Thanks!

**Comment by sierracircle** [comment]
That is actually a good idea.

I updated the script to have the option to include a log-file.  The file will be created in the same directory as the script, called services-log.
You have to uncomment the option in the top-area of the script

Let me know if that works for you.

**Comment by jomourad** [comment]
Log file works! 
Awesome and fast response!
