### ISSUE TITLE
Email not sent after crash

### ISSUE THREAD

**Issue by jomourad** [sierracircle/services-checker#16]
Looking at the closed issues, and one which was that the email wasn't sent, i configured my droplet for mail to be sent via sendmail (as you suggested to someone to install sendmail). Did some tests and server email works. However, not when the service crashes. Now, i am really FAR from knowing anything about this, but i noticed in your code, you use `echo $MESSAGE | mail -s "$SUBJECT" "$EMAIL"` but shouldn't it be `sendmail` instead of `mail`?

**Comment by sierracircle** [comment]
Hi. An easy way to test would be to just run a command from a terminal like:

`echo "This is a test messsage" | mail -s "This is the subject" "your@email.com"`
