### ISSUE TITLE
script is not working

### ISSUE THREAD

**Issue by saikiranmarripati** [sierracircle/services-checker#2]
I tried to use this script, take a look at how i configured it like below in **"crontab -e"**

`*/1 * * * * sh /var/www/html/jobs/services.sh`

I changed the email and stopped my apache2. I didn't get any email.

Can u pls help me in resolving this.

Thank you.

**Comment by sierracircle** [comment]
Hi @saikiranmarripati 
when you stopped apache2, did it start back up?
..if not, are you running the script as root? (you need to)
..did you change the permissions on the script to be executable?

To send mail, you need a MTA installed. Easiest is sendmail
`sudo apt install sendmail`

then (just choose defaults):
`sudo sendmailconfig`

**Comment by saikiranmarripati** [comment]
I have sendmail installed.

But when i run your script it says..

syntax error check them image below:

![image](https://user-images.githubusercontent.com/3437266/33416487-c9ac6700-d5c2-11e7-97ce-ede43315789f.png)

**Comment by sierracircle** [comment]
did you alter anything other than your email address? Did you make sure your email is in quotes?

**Comment by saikiranmarripati** [comment]
Check here, i just replaced my email Id

![image](https://user-images.githubusercontent.com/3437266/33416825-935c349e-d5c4-11e7-9c6b-2acdc45a0470.png)

**Comment by sierracircle** [comment]
what os are you running it on?

**Comment by saikiranmarripati** [comment]
ubuntu 14.04

**Comment by sierracircle** [comment]
one minute, let me double-check it is working still on one of my 14.04 machines. I just checked it in 16.04 (copied and pasted straight from github page) and it worked fine.

**Comment by sierracircle** [comment]
...wait. I think I see what the problem is: the quote on the right of your email looks a little funky. Do you have an extra single quote there?  Erase whatever is there and re-type a double-quote there.

**Comment by saikiranmarripati** [comment]
Email is clean in between double quotes as you said. there is nothing wrong in it.

**Comment by sierracircle** [comment]
Just to be sure there are no typos, here is the script copied directly from a 14.04 machine where I just tested it and it worked.  Try pasting this in to replace what you have there..

`
```
#!/bin/bash
#ver. 4
##this script will check mysql and apache
##if that service is not running
##it will start the service and send an email to you
##if the restart does not work, it sends an email and then exits

##set the path ##this works for Ubuntu 14.04 and 16.04
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

##set your email address 
EMAIL="your@email.com"

##list your services you want to check
SERVICES=( 'apache2' )

#### OK. STOP EDITING ####


 for i in "${SERVICES[@]}"
  do
 ###CHECK SERVICE####
 `pgrep $i >/dev/null 2>&1`
 STATS=$(echo $?)

 ###IF SERVICE IS NOT RUNNING####
 if [[  $STATS == 1  ]]

  then
  ##TRY TO RESTART THAT SERVICE###
  service $i start

  ##CHECK IF RESTART WORKED###
  `pgrep $i >/dev/null 2>&1`
  RESTART=$(echo $?)

  if [[  $RESTART == 0  ]]
   ##IF SERVICE HAS BEEN RESTARTED###
   then

    ##REMOVE THE TMP FILE IF EXISTS###
    if [ -f "/tmp/$i" ]; 
    then
     rm /tmp/$i
    fi

    ##SEND AN EMAIL###
    MESSAGE="$i was down, but I was able to restart it on on $(hostname) $(date)  "
    SUBJECT="$i was down -but restarted-  on $(hostname) $(date) "
    echo $MESSAGE | mail -s "$SUBJECT" "$EMAIL"

   else
    ##IF RESTART DID NOT WORK###

    ##CHECK IF THERE IS NOT A TMP FILE###
    if [ ! -f "/tmp/$i" ]; then

     ##CREATE A TMP FILE###
     touch /tmp/$i

     ##SEND A DIFFERENT EMAIL###
     MESSAGE="$i is down on $(hostname)  at $(date)  "
     SUBJECT=" $i  down on $(hostname) $(date) "
     echo $MESSAGE  " I tried to restart it, but it did not work"  | mail -s "$SUBJECT" "$EMAIL"
    fi
  fi
 fi



  done
exit 0;
```

`

**Comment by sierracircle** [comment]
any luck @saikiranmarripati ?

**Comment by saikiranmarripati** [comment]
Hey, Yeah i got it working by running it with bash not sh command.I am closing this issue.

**` bash  /var/www/html/jobs/services.sh`**

Thanks for your time.
