### ISSUE TITLE
Can't restart my nginx service

### ISSUE THREAD

**Issue by ghost** [sierracircle/services-checker#5]
I'm naive to bash script so please bear me and help me out here.
I added this service file at: /root/donotdelete

Then I added that path to the service file as well
Added my email address
In Services removed apache and mysql.
Then added 'nginx'
also added the code in crontab

Then I stopped my nginx service by this command "service nginx stop"
waited for 2 minutes, but it didn't restart.

Thank you

**Comment by sierracircle** [comment]
When troubleshooting this sort of thing, try running the script from a command-line first (before adding it to crontab)
So you would do:  
`sudo service nginx stop`
then:
`sudo /root/donotdelete`

Does that work? If not, does it give output?

**Comment by ksoares** [comment]
I am using the script as you have posted it here, but it always says the services are running, even if I command-line stop them as you noted in the above comment. I am stopping mysql, but the script believes it is still running. I am still trying to figure this out on my end, but would appreciate any insight.

Thanks
K.

**Comment by sierracircle** [comment]
are you running the script as root?

what OS are you using?

**Comment by ksoares** [comment]
Ubuntu 14.04 and yes, as root.

**Comment by sierracircle** [comment]
hmm.   if you have a cronjob set up, and you command-line stop the service, then the script is going to restart it..are you sure that is not what is happening?

**Comment by ksoares** [comment]
Yeah, it's very strange. First, I manually stop mysql with 'sudo service mysql stop'. It stops and my test website goes down.

I have your script running every 1 minute. I added some log file output to ensure that it is running. Every minute, it outputs that mysql is running. However, if I try to manually stop mysql again (same command as above), I get 'stop: Unknown instance:" meaning that no instance of mysql is running. So I am confused why the script thinks mysql is running, but neither the website nor a manual stop command agrees with that.

Thanks for any help.
K.

**Comment by ksoares** [comment]
It seems to come down to this statement:

 if [[  $STATS == 1  ]]

It is always false. I added an if/else snippet of code at the end of your script just as a test, and it always fires my 'else', even when I am certain mysql is not running.

**Comment by sierracircle** [comment]
You might try an earlier version of the script, which originally was created to run on 14.04.

**Comment by ksoares** [comment]
Thanks for the suggestion. What I am seeing is that 
STATS=$(echo $?)
always returns 0. This is the same whether I use the latest version of your script or the earliest one. I am trying both.

The reason I'm confused is because I think it *should* always return 0 - which is the exit status code for a successfully run command. Whether mysql is running or not, the exit status code for the command to check its status would always be 0. 

Maybe I am completely missing something, but it seems there is a disconnect between the exit status code for checking a service (which always works and returns 0) and getting the actual status of the service itself.

**Comment by sierracircle** [comment]
I tested the most recent version on an old 14.04 box I have. It worked fine with mysql only. I have not tried ngix yet
