### ISSUE TITLE
Will this work with 18.04? edit: Yes. Yes, it will.

### ISSUE THREAD

**Issue by appel** [sierracircle/services-checker#6]
Asking for a friend 😏

**Comment by sierracircle** [comment]
I have not tested in 18.04 yet. Can you try it and let me know?

**Comment by appel** [comment]
Just tried it, getting the following error:

> /usr/local/bin/services: 15: /usr/local/bin/services: Syntax error: "(" unexpected

This is line 15:

`SERVICES=( 'apache2' 'mysql' )`

I'm not exactly a linux ninja... ;) Do you know why it fails?

**Comment by sierracircle** [comment]
try removing  'mysql'  from the services and see if it still works...if it does, then I am guessing mysql uses some other syntax.

can you post the full error message?

**Comment by appel** [comment]
Looks like it was user error, @sierracircle, the script works perfectly fine as is on 18.04. Sorry about the confusion, closing this issue now.

Edit: I'll create a pull request to add 18.04 to the readme.

**Comment by sierracircle** [comment]
Thanks for checking things more closely and reporting back!
