### ISSUE TITLE
Is there a script that will work for "Ubuntu 18.04.1 LTS"?

### ISSUE THREAD

**Issue by heanth11** [sierracircle/services-checker#9]
Please help the one that is available is for ubuntu 14.04 and 16.04 only. Is there a services-checker for ubuntu 18.04.1?

**Comment by sierracircle** [comment]
have you tried it yet in 18.04?

**Comment by heanth11** [comment]
Yes, just to make sure I will be monitoring this script :) I will get back to you :) thanks!

**Comment by showket-ahmed** [comment]
> Yes, just to make sure I will be monitoring this script :) I will get back to you :) thanks!

Do you have any issue? Just set up with 18.04. I am also monitoring. If you have any issue, please let me know.

Regards
Showket Ahmed

**Comment by sierracircle** [comment]
I have it running on 18.04 for the last six months with no issues.

**Comment by showket-ahmed** [comment]
> I have it running on 18.04 for the last six months with no issues.

Great.
Thanks sierracircle.
